channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.6.10
  - aubio=0.4.9
  - librosa=0.7.2
  - pandas=1.0.1
  - joblib=0.14.1
  - matplotlib=3.2.0
  - scipy=1.4.1
  - click=7.0
  - yaafe=0.70
  - pip=20.0.2
  - plotly=4.7.0
  - tqdm=4.43
  - pyyaml=5.3.1
  - cachetools=3.1.1
